type Block =
  | { type: 'p'; text: string }
  | { type: 'h2'; text: string }
  | { type: 'h3'; text: string }
  | { type: 'break' };

export interface Article {
  title: string;
  date: string;
  content: Block[];
}

export const articles: Record<string, Article> = {

  'the-art-of-articulation': {
    title: 'The art of articulation',
    date: 'December 7, 2025',
    content: [
      { type: 'p', text: 'You are the verse I dare not write, yet dream nightly to read aloud.' },
      { type: 'p', text: 'There\u2019s a cruel intimacy between speaking our minds to strangers and failing to articulate our deepest thoughts to the people we love.' },
      { type: 'p', text: 'It seems the more someone matters, the heavier our words become.' },
      { type: 'p', text: 'Articulation isn\u2019t just saying what we feel. It\u2019s the vulnerability of being understood. It\u2019s the commitment to precision when imprecision feels safer.' },
      { type: 'p', text: 'We live in the gap between knowing and saying. And the distance kills us slowly.' },
      { type: 'p', text: 'You feel something, but the feeling sits in your chest instead of moving through your mouth. There are truths we cannot voice even as we shed tears over them, and emotions your body understands long before your vocabulary catches up. Somewhere between childhood and adulthood, that gap widens. The mind learns caution. The heart learns silence. And our ability to communicate what we actually mean becomes a sort of lost muscle.' },
      { type: 'break' },
      { type: 'h2', text: 'The Erosion' },
      { type: 'p', text: 'With AI slop plastered across every scroll, every billboard in SF (iykyk), the dreaded em dashes everywhere, the god-awful if-then statements infecting every paragraph, it\u2019s now more crucial than ever to be articulate.' },
      { type: 'p', text: 'Not just clear.' },
      { type: 'p', text: 'Articulate.' },
      { type: 'p', text: 'Articulation is not just saying what we feel. It is allowing ourselves to be understood and then living with whatever that understanding reveals. Most people think the hard part is finding the right wording. The real difficulty is surviving the exposure that comes with truth.' },
      { type: 'p', text: 'Articulation comes in different forms: the articulation of our words, and the articulation of our feelings. Ideally its us making sure what we say is exactly how we think. That the gap between internal and external shrinks until there\u2019s no room for misunderstanding.' },
      { type: 'break' },
      { type: 'h2', text: 'When did our voices die?' },
      { type: 'p', text: 'I keep thinking about when we actually stopped saying what we mean. Surely, it wasn\u2019t one moment, it had to been a collection of small ones, canon events that we have all felt. Telling someone you had a crush and getting silence back, getting laughed at for the wrong answer in class, or hearing adults say things they couldn\u2019t take back and learning how one bad conversation can change how two people look at each other forever.' },
      { type: 'p', text: 'Life trains honesty out of us.\nSo we start editing. Curating. Performing.' },
      { type: 'p', text: 'Social media honestly made it worse. Suddenly every IG caption had to sound like a Drake lyric, and work trained us to speak in corporate jargon. Somewhere along the way, we shrank our voice until it fit whatever space felt safest. And if I have to \u201Ccircle back\u201D one more time, I might actually lose it.' },
      { type: 'p', text: 'That saying exactly what you mean could cost you the job, the relationship, the friendship, the carefully constructed image you spent years building.' },
      { type: 'p', text: 'So we developed a new language: the language of implication, of reading between lines, of \u201Cyou know what I mean\u201D when neither person actually does.' },
      { type: 'p', text: 'We became fluent in ambiguity.' },
      { type: 'p', text: 'And somewhere along the way, we forgot how to just say what we mean.' },
      { type: 'p', text: 'The tragedy isn\u2019t that we can\u2019t articulate. It\u2019s that we chose not to, and now we\u2019re drowning in a sea of things we should\u2019ve said but didn\u2019t.' },
      { type: 'break' },
      { type: 'h2', text: 'On Relationships' },
      { type: 'p', text: 'I think the reason so many relationships feel more shallow than a kiddie pool in summer is because people don\u2019t actually articulate themselves. They don\u2019t get honest about how they feel.' },
      { type: 'p', text: 'Most relationships are built on convenience, location, or proximity. Not choice.' },
      { type: 'p', text: 'Whether platonic or romantic, what defines a relationship is commitment. But what are we doing to make that commitment strong? Are we maintaining intimacy through vulnerability? Through the hard work of being understood?' },
      { type: 'p', text: 'Language is commitment.' },
      { type: 'p', text: 'So why not give that commitment to yourself like you give it to your relationships?' },
      { type: 'p', text: 'It\u2019s why the right sentence can feel like liberation, and the wrong one like betrayal.' },
      { type: 'break' },
      { type: 'h2', text: 'The Cost of Silence' },
      { type: 'p', text: 'I had a friend once, the kind of friendship that feels permanent when you\u2019re young. We\u2019d stay up until 3 AM talking about everything, our fears, the futures we hoped we\u2019d grow into, whether we\u2019d ever actually live up to the versions of ourselves we talked about.' },
      { type: 'p', text: 'But life sped up, responsibilities stacked, and somewhere along the way our conversations got shorter. Lighter. Familiar but thin. I could feel something shifting, and I\u2019m sure he felt it too, but neither of us said anything. There wasn\u2019t a fight or a dramatic turning point. It was just two people avoiding an uncomfortable conversation, hoping the other would bring it up first. So the distance grew quietly until it felt easier to let the friendship fade than to ask what was happening.' },
      { type: 'p', text: 'Last I heard, he moved to Seattle. We haven\u2019t spoken in two years. People could say \u201Cwe grew apart,\u201D and maybe that\u2019s true, but part of me wonders if we just let the relationship starve because we were both too tired or too proud to be honest about what we were losing.' },
      { type: 'p', text: 'That\u2019s the real cost of silence.' },
      { type: 'p', text: 'Most relationships don\u2019t end with some big betrayal. They end when no one wants to be the one to say, \u201CSomething\u2019s off.\u201D By the time you realize you should have spoken, the window to fix it has already closed.' },
      { type: 'p', text: 'This relationship was a victim of a death not from conflict, but from things never said. Love that withers because neither person says what they need. Family members who carry decades of resentment over a conversation that never happened.' },
      { type: 'p', text: 'Because there is no right time to be honest.' },
      { type: 'p', text: 'There\u2019s just honest.' },
      { type: 'break' },
      { type: 'h2', text: 'The Practice' },
      { type: 'p', text: 'Lets be real, nobody just wakes up at 5 years old speaking like Henry David Thoreau, Carl Jung, or Shakespeare.' },
      { type: 'p', text: 'Though I haveth the wrong idea.' },
      { type: 'p', text: 'It takes repetition. Expressing your own emotions, vulnerabilities, and commitment to yourself. Daily. Relentlessly.' },
      { type: 'p', text: 'Be impeccable with your word.' },
      { type: 'p', text: 'And surprisingly enough, express yourself like a toddler.' },
      { type: 'p', text: 'If you think about it, they\u2019re humans in their purest form. Untouched by societal norms, without fear of judgment or embarrassment.' },
      { type: 'p', text: 'I was playing with Legos with a 4-year-old recently. The conversation shifted from his love for soccer, to asking why adults have to go to work, to asking me why I\u2019m not married.' },
      { type: 'p', text: 'Like dawg, what.' },
      { type: 'p', text: 'Zero filter. Zero fear.' },
      { type: 'p', text: 'Fascinating if you think about it. No filter, clear stream of thoughts, not a single worry in the world.' },
      { type: 'p', text: 'We have to be childlike. Curious.' },
      { type: 'p', text: 'Not afraid to say exactly what we\u2019re thinking, exactly how we\u2019re thinking it.' },
      { type: 'break' },
      { type: 'h2', text: 'The Work' },
      { type: 'p', text: 'We stall not because we don\u2019t know what to say.\nWe stall because saying it makes it real.' },
      { type: 'p', text: 'And the gap between knowing and saying is where relationships die.\nWhere intimacy withers.\nWhere we become strangers to ourselves and to the people we claim to love.' },
      { type: 'p', text: 'The lost skill isn\u2019t articulation.\nIt is the courage to be articulate when it matters.' },
      { type: 'p', text: 'Say the thing.' },
      { type: 'p', text: 'Call the friend. Send the text you keep rewriting. Tell the person you love that you love them.\nNot when you find the perfect sentence.' },
      { type: 'p', text: 'Now.' },
      { type: 'p', text: 'Because the cost of silence is always higher than the cost of honesty.' },
      { type: 'p', text: 'Truthfully, articulation is not a talent.' },
      { type: 'p', text: 'It is a refusal to hide behind vagueness when clarity would save us.' },
      { type: 'p', text: 'So be impeccable with your word.\nNot to sound profound.\nBut because every time you say exactly what you mean, you choose connection over comfort.' },
      { type: 'p', text: 'The world is full of beautiful liars and careful cowards.\nAnd you were not put here to be either.' },
      { type: 'p', text: 'Once you were the sentence I never said, and the silence I never recovered from.' },
      { type: 'p', text: 'But never again.' },
    ],
  },

  'the-skys-shake-but-my-heart-doesnt': {
    title: 'The sky\u2019s shake but my heart doesn\u2019t',
    date: 'December 18, 2025',
    content: [
      { type: 'p', text: 'I think I\u2019m afraid of flying.' },
      { type: 'p', text: 'There. I said it.' },
      { type: 'p', text: 'Which is absurd coming from someone who takes over 30+ flights a year. I don\u2019t really know where it started. It lives somewhere in the back of my brain, waiting. It\u2019s probably smaller than I make it out to be, but it is always there. A strange fear that only shows up once I am strapped into a seat, ears popping, cabin air smelling faintly of jet fuel and stale coffee, and the seatbelt sign chiming as a reminder that I am no longer in charge.' },
      { type: 'p', text: 'Imagine telling someone 120 years ago that one day, 200 people would sit inside an aluminum tube, flying 600 miles an hour, crossing oceans in a matter of hours. London to New York before your body even registers jet lag. It would have sounded like science fiction. Or arrogance. Or both.' },
      { type: 'p', text: 'I\u2019m writing this right now over the Atlantic Ocean. We just took off from London, and we have had two hours and thirty seven minutes of constant turbulence. Not the occasional bump. The kind that rattles your teeth. The kind where the wings look like they\u2019re flapping if you stare too long. The kind where even the flight attendants let out a small scream, which is concerning, because your entire job is to not do that. Like let me live a little and shriek too.' },
      { type: 'p', text: 'To make things better, they gave me the very last row on the plane. All the way in the back, next to the bathroom. Where you feel everything. Every dip, every drop, every reminder that physics is having a moment. I felt like a cowboy at a rodeo, hanging on for dear life, except the bull is 35,000 feet in the air.' },
      { type: 'p', text: 'I understand the physics. I know planes don\u2019t just fall out of the sky. I know turbulence is just uneven air. I know the pilot has control the entire time. None of that really helps.' },
      { type: 'p', text: 'Then it clicked.' },
      { type: 'p', text: 'It was never about flying.\nIt was never about altitude.\nIt was never about death.' },
      { type: 'p', text: 'It was about control.' },
      { type: 'break' },
      { type: 'h2', text: 'Two outcomes' },
      { type: 'p', text: 'What actually calms me is something darker and simpler. There are only two outcomes.' },
      { type: 'p', text: 'Either we land this plane, or this plane ends up in the Arctic Ocean and I am buried at sea next to the Titanic. Literally the same area. The only difference is I don\u2019t have a young Leonardo DiCaprio waiting to save me a spot on a floating door.' },
      { type: 'p', text: 'And honestly, I don\u2019t think this fear is a problem.' },
      { type: 'p', text: 'Flying will continue to exist whether I like it or not. Thirty seven million flights a year. Only a handful of accidents. Any rational person takes those odds. Yes, it is safer than driving a car. But rationality is a modern luxury. A hundred years ago, flight itself would have sounded reckless. Unnatural. A violation of how things were meant to be.' },
      { type: 'break' },
      { type: 'h2', text: 'Inheritance' },
      { type: 'p', text: 'When I hear stories about my grandfather traveling for hours, then days, then weeks, riding and sailing just to reach Hajj, I feel overwhelming gratitude that I can board a plane at all. I wish I could sit with him and ask what it felt like the first time he left the ground. What it meant to trust something he didn\u2019t fully understand, simply because the intention mattered more than the fear.' },
      { type: 'p', text: 'As the skies shake and the wings bend under pressure, I am confronted with the illusion of control.' },
      { type: 'p', text: 'I am just a passenger on this plane.' },
      { type: 'p', text: 'And that realization does something to me. Because this plane is life. This world is temporary. Fleeting. We are moving forward whether we like it or not, strapped into seats we didn\u2019t design, trusting systems we didn\u2019t build, headed toward destinations we don\u2019t fully see. The sooner you accept that you aren\u2019t in the cockpit, the lighter the ride becomes.' },
      { type: 'p', text: 'At the end of the day, everything we worry about is usually everything we have not trusted God with. Tawakkul is not passivity. It is clarity. It is knowing when effort ends and surrender begins.' },
      { type: 'p', text: 'People love to say, \u201CYou ain\u2019t the passenger, you\u2019re the pilot.\u201D It sounds empowering. It sells books. But the moment you realize no one knows the exact route, how much fuel is left, or when turbulence hits, you understand the truth. We are all passengers. Every single one of us. Just trying to act confident while the seatbelt sign flickers on and off.' },
      { type: 'break' },
      { type: 'h2', text: 'The illusion of control' },
      { type: 'p', text: 'We live in an age obsessed with control.\nSelf control sermons clipped into short videos.\nBrands trying to control narratives when their PR collapses.\nPeople mapping out five year plans like the future read the Notion doc and agreed.' },
      { type: 'p', text: 'Even self sabotage is rooted in control. We sabotage because it lets us predict pain. If we cause it, at least it is familiar. If we ruin something ourselves, we don\u2019t have to sit with the terror of losing it unexpectedly. Control becomes a shield, even when it hurts us.' },
      { type: 'p', text: 'This isn\u2019t an essay about predestination, or debates about what is written. This is about letting go of what was never ours to hold. Yes, take responsibility for your life. Build. Act. Move. Create impact. But stop pretending you are meant to carry the weight of outcomes you cannot influence. That illusion is what feeds anxiety, depression, and quiet despair.' },
      { type: 'p', text: 'If something isn\u2019t within your immediate ability to change, decide, or meaningfully affect, then it isn\u2019t worthy of your constant worry. You ain\u2019t behind. You are not late. You are exactly where you need to be.' },
      { type: 'p', text: 'I think about this like premature engineering, the death of good builders. Over optimizing systems before the problem exists. Burning energy solving hypothetical failures.' },
      { type: 'p', text: 'Life works the same way.' },
      { type: 'p', text: 'You deal with problems when they arrive. Planning is useful when outcomes are clear. But in life, no one knows what happens on any timeline. The attempt to control everything does not make you safer. It just makes you tired.' },
      { type: 'p', text: 'You cannot control the wind, but you can adjust your sails.\nSo grow with the flow.' },
      { type: 'break' },
      { type: 'h2', text: 'Letting the ride continue' },
      { type: 'p', text: 'Somewhere in the middle of all this shaking, I tried talking to the woman next to me. A seventy year old Polish woman from Chicago. Sometimes speaking to a stranger helps normalize fear. Before I could even say anything, she sensed it. She smiled gently and said, \u201CWe will be alright.\u201D' },
      { type: 'p', text: 'We talked. She told me about her grandson, how proud she was of him, all his accomplishments. At some point, I realized we were the same age, in the same profession.' },
      { type: 'p', text: 'It made me think about how little time I had with my own grandparents. They lived on different continents, in a world where flying was rare and distance actually meant something. So I didn\u2019t see them the way this woman saw her grandson. I let her words land where they needed to. Maybe she was projecting. Maybe I was receiving something I didn\u2019t know I had been missing.' },
      { type: 'p', text: 'She wasn\u2019t afraid, not of the turbulence nor of the uncertainty. She\u2019d lived long enough to know that worrying about the plane doesn\u2019t change whether it lands.' },
      { type: 'p', text: 'The turbulence continued. The wings kept bending. But I stopped gripping the armrest as tight. The plane keeps moving forward.' },
      { type: 'p', text: 'So does life.' },
      { type: 'p', text: 'I let my heart learn what this little old lady already knew. Turbulence is not the enemy, resistance is.' },
      { type: 'p', text: 'Trusting the ride doesn\u2019t mean you\u2019re weak.\nIt means you finally understand how little you were meant to carry.' },
    ],
  },

  'the-museum-of-unlived-lives': {
    title: 'The museum of unlived lives',
    date: 'November 13, 2025',
    content: [
      { type: 'h3', text: 'A tour of the versions of me I never became.' },
      { type: 'p', text: 'There\u2019s a strange silence you only hear in coastal towns; the kind that forces you to sit with yourself. I\u2019m writing this from Livorno, a small fishing city on Italy\u2019s western coast. The waves are sharp, the food is sharper, and the whole town smells like olive oil, rusted boats, and old stories.' },
      { type: 'p', text: 'As I approach my 25th birthday and dive into this spiral of reflection; choices made, choices avoided, I\u2019m stunned by how far I\u2019ve come. People keep asking me, \u201CSo what\u2019s next?\u201D' },
      { type: 'p', text: 'Honestly, the only real way to answer that is to look at where I\u2019ve been.' },
      { type: 'p', text: 'And when I look back, I see something strange:' },
      { type: 'p', text: 'the versions of me I never became.' },
      { type: 'p', text: 'So many choices I didn\u2019t make pushed me into the man I am today. Lessons, losses, heartbreaks, and on the flip side, the beautiful experiences that make life worth living. My only rule has been to never carry regret. Never let regret take a seat at the table.' },
      { type: 'p', text: 'Now with a fully formed prefrontal cortex (allegedly), I walk through the museum of the lives I never lived.' },
      { type: 'p', text: 'And it feels like death. The death of every version of me that never saw the light of day.' },
      { type: 'break' },
      { type: 'h2', text: 'The Attempts That Built Me' },
      { type: 'p', text: 'Anyone who knows me knows I\u2019ve tasted almost everything under the sun. If something seems remotely interesting, I have to try it.' },
      { type: 'p', text: 'Welding robots in a machine shop.' },
      { type: 'p', text: 'Taking classes on being a florist.' },
      { type: 'p', text: 'Directing short films.' },
      { type: 'p', text: 'Representing people in court. (please don\u2019t ask how I got there)' },
      { type: 'p', text: 'Not for aesthetics. Not for r\u00E9sum\u00E9 points. But to be able to say I actually lived. I actually tried. Life is more about attempting than anything else.' },
      { type: 'p', text: 'And the attempts, even the stupid ones, built me.' },
      { type: 'p', text: 'I hopped onto a fishing boat this morning just to see what rough seas could teach me about control. I ended up talking to an older Italian fisherman whose wisdom weighed more than every foam-topped wave around us.' },
      { type: 'p', text: 'Talking to strangers in foreign countries is one of my favorite ways to understand the human condition. They\u2019ll tell you truths you can\u2019t pull out of yourself. He told me something simple:' },
      { type: 'p', text: 'When you die and look back, all you\u2019ll have are your memories. Nothing else. Because you have nothing left to experience.' },
      { type: 'p', text: 'The laughs. The scars. The experiences. Then you die.' },
      { type: 'p', text: 'So you might as well create the memories you actually want. To have lived the life you claimed you wanted. The dream.' },
      { type: 'p', text: 'He said the most bitter people he\u2019s met weren\u2019t the people who tried and failed; they were the people who never tried at all.' },
      { type: 'p', text: 'Kinda makes sense why some of the grumpiest people in the world are old.' },
      { type: 'break' },
      { type: 'h2', text: 'Every Choice Is a Death' },
      { type: 'p', text: 'The more I sat with his words, the more it clicked:' },
      { type: 'p', text: 'Every decision is a death.' },
      { type: 'p', text: 'When you choose business, you kill artist-you. When you choose this city, you kill that-city-you. When you marry or don\u2019t marry someone, you kill that timeline.' },
      { type: 'p', text: 'And in every pivot of my unorthodox career, hardware engineering, law, venture capital, non-profit, computer science, I killed off a version of myself. Whether I realized it or not. Every pivot was a silent funeral for a version of Ayman that wasn\u2019t meant to make it.' },
      { type: 'p', text: 'But here\u2019s the thing most people don\u2019t want to admit:' },
      { type: 'p', text: 'The weight of an unmade decision is the heaviest thing in the world.' },
      { type: 'p', text: 'People aren\u2019t scared of failure. They\u2019re scared of success. They\u2019re scared to accept how achievable their goals actually are.' },
      { type: 'p', text: 'Because once you understand everything you want is reachable, you lose every excuse you had. You have to act. You have to hold yourself accountable. And there\u2019s nothing left to hide behind.' },
      { type: 'p', text: 'So they freeze. And the unmade decision slowly crushes them. Making life unbearable.' },
      { type: 'break' },
      { type: 'h2', text: 'Learning to Walk Through the Museum' },
      { type: 'p', text: 'So how do you reconcile all these deaths?' },
      { type: 'p', text: 'You visit the museum.' },
      { type: 'p', text: 'You walk the hallways of the unlived lives.' },
      { type: 'p', text: 'You acknowledge the versions of yourself that didn\u2019t make it.' },
      { type: 'p', text: 'Not to fantasize about what could\u2019ve been, but to be grateful for what actually was. To get closure. To accept qadr.' },
      { type: 'p', text: 'I hate the \u201Cwhat if\u201D game. Truly. It\u2019s fear dressed up in assumptions and pity. A way for people to feel better about never acting in the first place.' },
      { type: 'p', text: 'Because honestly?' },
      { type: 'p', text: 'The bar for trying is so low.' },
      { type: 'p', text: 'Most people won\u2019t have the memories because they were scared.' },
      { type: 'p', text: 'I\u2019d rather walk through a museum full of skeletons labeled attempts than live with regret.' },
      { type: 'p', text: 'Growth is choosing which version of you deserves to live.' },
      { type: 'break' },
      { type: 'h2', text: 'A Meditation' },
      { type: 'p', text: 'Visit the museum of your unlived lives.' },
      { type: 'p', text: 'What would Ayman-who-became-a-doctor be doing right now?' },
      { type: 'p', text: 'Ayman-who-moved-to-Mecca?' },
      { type: 'p', text: 'Ayman-who-stayed-broke-but-happy?' },
      { type: 'p', text: 'Don\u2019t dwell, just be grateful.' },
      { type: 'p', text: 'Look at that fisherman. He wakes up before sunrise, pushes his boat into the water, and plays the same game every day because he loves it. Not many people love the game.' },
      { type: 'p', text: 'What you\u2019re not changing is what you\u2019re choosing.' },
      { type: 'p', text: 'So make sure every failure happens because something was out of your control. Not because you didn\u2019t attempt. Collect the bodies on the path to failure until you see what\u2019s real.' },
      { type: 'p', text: 'Stay in the tension.' },
      { type: 'p', text: 'The only fear worth carrying is the fear of not reaching the outcome.' },
      { type: 'p', text: 'The further you entertain what\u2019s not for you, the longer you delay what is. Success hits different when you sacrifice the life you thought you wanted for the one you actually need.' },
      { type: 'p', text: 'Sometimes I laugh at the old versions of my reasoning. Now it\u2019s simpler:' },
      { type: 'p', text: 'Align the north star with the man I want to become.' },
      { type: 'p', text: 'The man my ancestors would be proud of.' },
      { type: 'p', text: 'The man my descendants will claim proudly.' },
      { type: 'p', text: 'And as I stand on the edge of whatever comes next, I walk through my museum in silence; the fishermen shouting in the distance, the Italian sun hitting the water, and the ghosts of the unlived versions of me lining the walls.' },
      { type: 'p', text: 'It gives me the clarity to pull the trigger on the versions of Ayman that need to die, kill the versions of Ayman that don\u2019t serve the mission\u2026' },
      { type: 'p', text: 'and resurrect the one that will.' },
    ],
  },

  'grief': {
    title: 'Grief',
    date: 'July 8, 2023',
    content: [
      { type: 'p', text: 'Bismillah' },
      { type: 'p', text: 'Grief is just love with no place to go.' },
      { type: 'p', text: 'People all grieve. Some are different than others, but we can all agree that there is just this sense of emptiness that we all perceive.' },
      { type: 'p', text: 'It is a feeling where you notice everything moving around you, but it feels like time has stopped. Where sounds don\u2019t hear the same anymore, colors are dull, and flavors are bland. When nothing matters other than to sit in the moment and feel empty.' },
      { type: 'p', text: 'Whether you have lost a loved one, been laid off, or been stuck with tragedy, the moment you hear the news, you feel the world\u2019s weight drop into your stomach.' },
      { type: 'p', text: 'Knowing there is nowhere to hide, without a place to run to.' },
      { type: 'p', text: 'That weight feels unbearable. But it isn\u2019t something you haven\u2019t felt before.' },
      { type: 'break' },
      { type: 'h2', text: 'A sad reality' },
      { type: 'p', text: 'I was at an airport headed to Phoenix, Arizona, recently, and I sat next to this man; relatively my age, it looked like he could be a distant relative or a cousin based on looks.' },
      { type: 'p', text: 'After being intrigued by how similar we looked and dressed, I had to start a conversation.' },
      { type: 'p', text: 'After sitting down, I see him and instantly realize that he is uncomfortable and jittery. Pacing back and forth, wanting to avoid hopping on that plane.' },
      { type: 'p', text: 'Fearing the destination.' },
      { type: 'p', text: 'After sparking a conversation to calm this man down, I ask him. \u201CHow ya living?\u201D His response shocked me.' },
      { type: 'p', text: '\u201CIn between 6 feet under and paradise.\u201D' },
      { type: 'p', text: 'A very unusual way to put this Dunya, a genuinely unique perspective.' },
      { type: 'p', text: 'After trying to wrap my head around what that meant, my inquisitive nature kept poking to figure out what elicited this response.' },
      { type: 'p', text: 'Learning that the man was on the way to bury his uncle, who passed away a few hours ago, I lent an ear to listen to his sorrow and provided my shoulder to be cried on. His uncle was nearing old age but still had a lot of life in him; that man processed his grief the only way he knew how, by looking at the reality of death in the face of this emotional rollercoaster. His somewhat optimistic but scary reality and outlook was an impactful moment I hold dear.' },
      { type: 'p', text: 'That moment instantly changed my brain chemistry and allowed me to dive deep and understand the grief around my life and experiences.' },
      { type: 'break' },
      { type: 'h2', text: 'It\u2019s personal' },
      { type: 'p', text: 'Death, for example, happens every day. But when it\u2019s personal or about you, that\u2019s when it matters.' },
      { type: 'p', text: 'A dear friend of mine wants to tell me a quote that he got from, crazy enough, Dictator Joseph Stalin.' },
      { type: 'p', text: '\u201CThe death of 1 man is a tragedy. But the death of millions is just a statistic.\u201D' },
      { type: 'p', text: 'When it is personal, that\u2019s when the world stops. But it becomes much easier to bear when it\u2019s halfway across the world where the atrocities don\u2019t impact you. In reality, we can\u2019t be selfish with the process of understanding death, grieving; however, it is a natural progression of life; there isn\u2019t much we can do afterward.' },
      { type: 'p', text: 'When it is personal, the love of the person that left now has no place in this world. That place where love could go, left with them. So the love becomes frustrated with itself and eats itself from within. Looking for a place to just be sent.' },
      { type: 'p', text: 'All the goodbyes and love you always meant to give them but never got the chance to. All pent up, waiting for the release like a river being held up by a dam.' },
      { type: 'p', text: 'But the only thing that floods are your tears.' },
      { type: 'p', text: 'Uncontrollably flowing, tears rush until the wetness of your beard starts painting on your shirt, which, when looking at the whole frame, seems only like a beautifully tragic scene that only Van Gogh, Goya, or Picasso can depict.' },
      { type: 'p', text: 'I\u2019m not a painter, but you get the picture.' },
      { type: 'break' },
      { type: 'h2', text: 'Advice' },
      { type: 'p', text: 'The age-old question becomes how do we reconcile where the love goes before it comes to grief?' },
      { type: 'p', text: 'That is a beautiful question. I don\u2019t have any answers, but I do have some advice.' },
      { type: 'p', text: 'Not living with regret is a good place to start.' },
      { type: 'p', text: 'In reality, truth doesn\u2019t need agreement or care for your emotion. Truth moves forward. Just like the rest of the world.' },
      { type: 'p', text: 'Like anything else, these types of grief will take time to come to terms with.' },
      { type: 'p', text: 'But the grief that will live on forever, is the grief of regret. That is a weight that no one else can bear.' },
      { type: 'p', text: 'Making sure every interaction you have is intentional with total effort. Leaving everything on the table.' },
      { type: 'p', text: 'All the emotions you shoulda said or probably should have refrained from.' },
      { type: 'p', text: 'All the flowers you didn\u2019t give.' },
      { type: 'p', text: 'At the end of the day, more people regret things they didn\u2019t do rather than what they did.' },
      { type: 'p', text: 'If this is a sign for you to do something, go for it.' },
      { type: 'p', text: 'The fear of regret far outweighs the fear of failure.' },
      { type: 'p', text: 'If you focus on the hurt, you\u2019ll continue to suffer. If you focus on the lesson, you will continue to grow.' },
      { type: 'p', text: 'So learn the lesson before the grief sets in. And let the comfort of an attempt set you free.' },
    ],
  },

  'critically-unacclaimed': {
    title: 'Critically unacclaimed',
    date: 'June 2023',
    content: [
      { type: 'p', text: 'Bismillah' },
      { type: 'p', text: 'Just like releasing this writing publicly, I am attempting to do something for the first time. Skiing. There is this sense of hesitation that I have staring down this mountain, a concoction of fear and doubt.' },
      { type: 'p', text: 'A place where toddlers are zooming past me at what looks like unsafe speeds, with all the confidence in the world. Consistent thoughts of dread, plaguing my mind on whether or not I should try and attempt to actually go down.' },
      { type: 'p', text: 'It begs the question, was I scared of the mountain? Or was I afraid of the humility that comes with failing? It became evident that it was the latter.' },
      { type: 'p', text: 'After trying to hop on the skis, and the first few humbling attempts falling on my butt, something clicked. No I didn\u2019t become good at skiing all of a sudden (I am still trash lol), I made a realization that \u201Cthe attempt is far more important than the end result.\u201D' },
      { type: 'p', text: 'This attempt at skiing was a reminder that 100 billion people lived before me. Anything that I do cannot and will not be the first attempt, I am a nobody. Thoughts, actions, problems, all have been attempted and solved by literally all of humanity.' },
      { type: 'p', text: 'At the end of the day it was just me vs a mountain, and I definitely wasn\u2019t the first person in the world who was scared going down a mountain. So I mustered up the courage and the solution became clear. Just go down the mountain. Regardless of the pitfalls of failure.' },
      { type: 'p', text: 'The answer seemed so trivial. Right in front of me, but the tension and stress of what the external world thinks of my failure, was clouding the judgement.' },
      { type: 'p', text: 'On the flip side, there is also a sense of comfort that I feel knowing that I can\u2019t have an original thought or feeling. That whatever problem I might be having, someone else has solved it. A sense of comfort that there is no reason to not attempt, because the results are already there.' },
      { type: 'p', text: 'After some greater reflection, these thoughts permeated into something greater.' },
      { type: 'p', text: 'If so many people have tried literally everything, how can I be different? In all aspects of life, not just this mountain I had to go down.' },
      { type: 'p', text: 'To me this experience going down this mountain was new, but to the rest of the world it wasn\u2019t. I wasn\u2019t original nor creative in its solution.' },
      { type: 'break' },
      { type: 'h2', text: 'The originality paradox' },
      { type: 'p', text: 'Creativity elicits a feeling of being different, that makes people unique.' },
      { type: 'p', text: 'The idea of originality makes it seem like we have to try to become different. But in reality we aren\u2019t. It\u2019s nearly impossible to have an original thought, but we force ourselves to make that effort to feel\u2026different.' },
      { type: 'p', text: 'This seeps into almost every aspect of your life. Especially, creating.' },
      { type: 'p', text: 'I had a lovely conversation with my dear friend Haroon Dean, who is a phenomenal writer and a pure soul. He wrote an epic piece about that very same conversation around how \u201Cpeople NEED to create.\u201D It inspired me to find an outlet to release some of my essays, writings, and thoughts that I\u2019ve had for years.' },
      { type: 'p', text: 'Keeping the writings for myself does me no benefit, nor society. But if releasing it allows me to become more comfortable around my own creativity, let the promise of the pen write the truth.' },
      { type: 'p', text: 'People have this fear of creating, driven by hesitation from societal factors on what the world thinks. But on the other side, some people over-create for the validation of other people or the search to be \u201Cdifferent.\u201D It makes people feel that they need an external factor to do things and create.' },
      { type: 'p', text: 'Regardless of your intentions, create.' },
      { type: 'p', text: 'Truthfully, no one cares. Not your mother, not your 67 instagram followers, not your 3rd grade teacher that you hated. No one cares what you do. We live in such a self centered society that, \u201Cyou\u201D being at the center of it, we as humans don\u2019t have the capacity to wonder or even care about what anyone else is doing. So it doesn\u2019t even matter. If you truly cared about building something, you would do it. Regardless of the response or the accolades.' },
      { type: 'p', text: 'So I attempt this challenge, first and foremost for myself, and I urge everyone else to do so, to create. In any medium, fashion, or method. Naturally people create everyday unknowingly, but as soon as you become intentional in your creativity, it creates this momentum that allows you to continue.' },
      { type: 'p', text: 'I have many different creative outlets, and I hopefully will use this essay platform to enhance those creative skills. But by writing and documenting this journey, I hope to sharpen my penmanship like a soldier prepping their sword for battle.' },
      { type: 'break' },
      { type: 'h2', text: 'Being Critical' },
      { type: 'p', text: 'Most people (like myself) are our own biggest critic. The problem with that is that we haven\u2019t won anything yet. I don\u2019t have any accolades, or awards for my writing. No piece of creativity has been praise worthy or acclaimed. We have to let the world decide that. But that only occurs, when we actually open our hearts, when we release, when we publish.' },
      { type: 'p', text: 'If the world hasn\u2019t judged your work yet, why have you?' },
      { type: 'p', text: 'We are all just trying out in this world, and regardless of the accolades and attempts we try to make into it. Whether you have written 1 piece, or 100. Attempted to paint once or have an entire gallery of work that hasn\u2019t seen the light of day. We are all the same.' },
      { type: 'p', text: 'Just like critically acclaimed films, albums, or novels, they all started in the minds of people. The difference between us and them is they actually took the steps to release it to the world. To receive its judgement. To face its harsh truth.' },
      { type: 'p', text: 'At the beginning it\u2019s going to be hard, and might not turn out that good, but it doesn\u2019t matter, because my best work is always going to be the next one. We first have to tear down these arbitrary walls about being critical, because we are unacclaimed. We have no place in the hearts of people yet.' },
      { type: 'p', text: 'At the end of the day no one is special, but everyone can become special, with the right eyes looking. To find the value deep down requires a strength that very few possess. But to release it in the public, requires an even greater amount of confidence.' },
      { type: 'p', text: 'But until we release our work, we all are just' },
      { type: 'p', text: 'Critically Unacclaimed' },
    ],
  },

};
